among_us_friends/blueprints/games.py
from uuid import UUID

from flask import Blueprint, render_template, url_for
from flask_login import login_required, current_user
from werkzeug.exceptions import Unauthorized
from werkzeug.utils import redirect

from among_us_friends import games_controller
from among_us_friends.blueprints import open_repository
from among_us_friends.game import Game

games = Blueprint('games', __name__)


@games.route('/games/<game_id>')
@login_required
def game(game_id):
    game: Game = games_controller.get_game(UUID(game_id))
    admin_rights = game.owner_id = current_user.uuid
    return render_template('game.html', game=game, admin_rights=admin_rights, user=current_user)


@games.route('/games/<game_id>/delete')
@login_required
def delete(game_id):
    uuid = UUID(game_id)
    with open_repository() as repo:
        game = Game(repo, uuid)
        if current_user.uuid != game.owner.uuid:
            raise Unauthorized()
        room = repo.room_dao().get_by_rowid(game.room_id)
        repo.game_dao().delete_by_uuid(uuid)
        repo.commit()
    return redirect(url_for('rooms.room', room_id=room.uuid.hex))


@games.route('/games/<game_id>/admin')
@login_required
def game_admin(game_id):
    with open_repository() as repo:
        game = Game(repo, UUID(game_id))
        if current_user.uuid != game.owner.uuid:
            raise Unauthorized()
        return render_template('game_admin.html', game=game, user=current_user)


@games.route('/games/<game_id>/admin', methods=['POST'])
@login_required
def game_admin_post(game_id):
    with open_repository() as repo:
        repo.match_dao().create()

among_us_friends/blueprints/lobbies.py
from uuid import UUID

from flask import Blueprint, render_template, url_for, request, current_app
from flask_login import current_user, login_required
from werkzeug.utils import redirect

from among_us_friends.blueprints import open_repository


lobbies = Blueprint('lobbies', __name__)


@lobbies.route('/lobbies/create')
def new_lobby():
    return render_template('new_lobby.html')


@lobbies.route('/lobbies/<lobby_id>')
@login_required
def lobby(lobby_id):
    lobby_uuid = UUID(lobby_id)
    with open_repository() as repo:
        lobby = repo.lobby_dao().require_lobby(lobby_uuid)
        rooms = repo.room_dao().list_for_lobby(lobby)
    rooms = list(rooms)
    return render_template('lobby.html', lobby=lobby, rooms=rooms, user=current_user)


@lobbies.route('/lobbies/create', methods=['POST'])
@login_required
def create_lobby():
    form = request.form
    title = form['title']
    anyone = bool(form.get('anyone', 'off') == 'on')
    with open_repository() as repo:
        lobby = repo.lobby_dao().create(title, anyone)
    return redirect(url_for('lobby', lobby_id=lobby.uuid.hex))


@lobbies.route('/lobbies/<lobby_id>/makeRoom')
@login_required
def create_room(lobby_id: str):
    return render_template("new_room.html")


@lobbies.route('/lobbies/<lobby_id>/makeRoom', methods=('POST',))
@login_required
def post_create_room(lobby_id: str):
    form = request.form

    room_title = form['title']

    with open_repository() as repo:
        lobby = repo.lobby_dao().require_lobby(UUID(lobby_id))
        room = repo.room_dao().create(lobby, room_title)
        repo.commit()
    return redirect(url_for('rooms.room', room_id=room.uuid.hex))

among_us_friends/blueprints/rooms.py
from uuid import UUID

from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from among_us_friends import games_controller
from among_us_friends.blueprints import open_repository
from among_us_friends.room_correlations import HtmlRoomCorrelationsFormatter, RoomCorrelations
from among_us_friends.games import HtmlGamesFormatter
from among_us_friends.imposter_stat import HtmlImposterStatsFormatter
from among_us_friends.stats import PlayersMatchesStats, ColorsMatchesStats
from among_us_friends.repository import NotFoundException

rooms = Blueprint('rooms', __name__)


@rooms.route("/rooms/<room_id>")
@login_required
def room(room_id):
    mode = request.args.get('mode', '%')
    room_uuid = UUID(room_id)
    games = games_controller.get_games_for_room(room_uuid)
    print(games)
    with open_repository() as repo:
        try:
            room = repo.room_dao().require_room(room_uuid)
        except NotFoundException:
            abort(404)
        matches = list(repo.match_dao().list_for_room(room, mode))
        lobby_id = repo.lobby_dao().get_by_rowid(room.lobby).uuid.hex
        counts = repo.result_dao().counts_by_match_rowid_for_room(room)
        player_stats = list(PlayersMatchesStats(matches).using(repo))
        color_stats = list(ColorsMatchesStats(matches).using(repo))
        correlations = RoomCorrelations(room, matches).using(repo)
    counts = dict(counts)
    matches = {m.rowid: m for m in matches}
    match_counts = ((matches.get(k, None), counts.get(k, None)) for k in counts.keys() | matches.keys())
    return render_template(
        'room.html', room=room, match_counts=match_counts, user=current_user,
        lobby=lobby_id,
        games=HtmlGamesFormatter(games),
        player_stats=HtmlImposterStatsFormatter(player_stats),
        color_stats=HtmlImposterStatsFormatter(color_stats),
        correlations=HtmlRoomCorrelationsFormatter(correlations)
    )


@rooms.route('/rooms/<room_id>/createGame', methods=['GET', 'POST'])
@login_required
def create_game(room_id):
    if request.method == 'GET':
        return render_template('new_game.html')
    title = request.form['title']
    user = current_user
    game_id = games_controller.create_game(user, room_id, title)
    return redirect(url_for('games.game', game_id=game_id))

among_us_friends/blueprints/users.py
from uuid import UUID

from flask import Blueprint, render_template, url_for

from among_us_friends.blueprints import open_repository

users = Blueprint('users', __name__)


@users.route('/users')
def all_users():
    ret = '<ul>'
    with open_repository() as repo:
        for user in repo.user_dao().list():
            ret += f'<li><a href={url_for("users.user", user_id=user.uuid.hex)}>{user.username}</a></li>'
    ret += '</ul>'
    return ret


@users.route('/users/<user_id>')
def user(user_id):
    with open_repository() as repo:
        user = repo.user_dao().require_uuid(UUID(user_id))
    return render_template('user.html', user=user)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/base.css') }}">
    {% endblock %}
</head>
<body>
<div id="header">
    <div id="head-ident">{% block header_nav %}{% endblock %}</div>

    <h2 class="hitem" id="username">{{ user.username }}</h2>
    {% if user is none or not user.is_authenticated %}
    <a class="hitem" href="{{ url_for('login') }}">Login</a>
    {% else %}
    <a class="hitem" href="{{ url_for('logout') }}">Logout</a>
    {% endif %}
</div>
<div id="content">{% block content %}{% endblock %}</div>
</body>
</html>

templates/game.html
{% extends "base.html" %}
{% block title %}{{ game.title }}{% endblock %}
{% block header_nav %}
<a class="hnav" href="{{ url_for('rooms.room', room_id=game.room) }}">Back to Room</a>
{% if admin_rights %}
<a class="hnav" href="{{ url_for('games.game_admin', game_id=game.uuid) }}">Game Admin</a>
{% endif %}
{% endblock %}
{% block content %}

{% endblock %}

templates/game_admin.html
{% extends "base.html" %}
{% block title %}{{ game.title }}{% endblock %}
{% block header_nav %}
<a class="hnav" href="{{ url_for('games.game', game_id=game.uuid.hex) }}">Back to Game</a>
<a class="hnav" href="{{ url_for('games.delete', game_id=game.uuid.hex) }}">Close Game</a>
{% endblock %}
{% block content %}
<form>
    <div>
        <label for="title">Match Title</label>
        <input id="title" type="text" name="title" value="{{ game.match_title }}">
    </div>
    <div>
        <label for="host">Game Host</label>
        <input id="host" type="text" name="host" value="{{ game.host }}">
    </div>
    <div>
        <label for="players">Num Players</label>
        <input id="players" type="text" name="players" value="{{ game.players }}">
    </div>
    <div>
        <label for="mode">Mode</label>
        <input id="mode" type="text" name="mode" value="{{ game.mode }}">
    </div>
    <div>
        <label for="map">Map</label>
        <input id="map" type="text" name="map" value="{{ game.map }}">
    </div>
    <div>
        <label for="result">Result</label>
        <input id="result" type="text" name="result" value="{{ game.result }}">
    </div>
    <div>
        <label for="network">Network</label>
        <input id="network" type="text" name="network" value="{{ game.network }}">
    </div>
    <input type="submit" formmethod="post">
</form>
{% endblock %}

templates/index.html
<html>
<head>
    <title>Among Us Friends</title>
</head>
<body>
<h1>Lobbies</h1>
<a href="{{ url_for('lobbies.new_lobby') }}">Create a New Lobby</a>
<ul>
    {% for item in lobbies %}
    <li>
        <a href="{{ url_for('lobbies.lobby', lobby_id=item.uuid.hex) }}">{{ item.title }} </a>
    </li>
    {% endfor %}
</ul>
<h1>Users</h1>
<a href="users">Users</a>
</body>
</html>

templates/lobby.html
{% extends "base.html" %}
{% block title %}{{ lobby.title }}{% endblock %}
{% block content %}
<body>
<p>This is a {% if lobby.anyone %} public {% else %} private {% endif %} lobby</p>
<div>
    <h2>Rooms</h2>
    <button onclick="window.location.href='{{ url_for('lobbies.create_room', lobby_id=lobby.uuid.hex) }}'">Create Room</button>
    <ol>
        {% for room in rooms %}
        <li><a href="{{ url_for('rooms.room', room_id=room.uuid.hex) }}">{{ room.title }}</a></li>
        {% endfor %}
    </ol>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
</head>
<body>
<form>
    <div>
        <label for="username">Username</label>
        <input id="username" type="text" name="username">
    </div>
    <div>
        <label for="password">Password</label>
        <input id="password" type="password" name="password">
    </div>
    <div>
        <label for="remember">Remember Me</label>
        <input id="remember" type="checkbox" name="remember">
    </div>
    <input type="submit" formmethod="post">
</form>
</body>
</html>

templates/new_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Game</title>
</head>
<body>
<form>
    <div>
        <label for="title">Game Title</label>
        <input id="title" type="text" name="title">
    </div>
    <div>
        <input type="submit" formmethod="post">
    </div>
</form>
</body>
</html>

templates/new_lobby.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a new Lobby</title>
</head>
<body>
<h1>Create a New Lobby</h1>
<div>
    <a href=" {{ url_for('index') }}">Go Back</a>
</div>
<form>
    <div>
        <label for="title">Lobby Title</label>
        <input id="title" type="text" name="title">
    </div>
    <div>
        <label for="anyone">Public Lobby?</label>
        <input id="anyone" type="checkbox" name="anyone">
    </div>
    <div>
        <input type="submit" formmethod="post">
    </div>
</form>
</body>
</html>

templates/new_room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Room</title>
</head>
<body>
<div>
    <a href="..">Go Back</a>
</div>
<form>
    <div>
        <label for="title">Room Title</label>
        <input id="title" type="text" name="title">
    </div>
    <div>
        <input type="submit" formmethod="post">
    </div>
</form>
</body>
</html>

templates/room.html
{% extends "base.html" %}
{% block title %}{{ room.title }}{% endblock %}
{% block header_nav %}
<a class="hnav" href="{{ url_for('lobbies.lobby', lobby_id=lobby) }}">Lobby</a>
{% endblock %}
{% block content %}
<div>
    <h1>Games</h1>
    <button onclick="window.location.href='{{ url_for('rooms.create_game', room_id=room.uuid.hex) }}'">
        Make New Game</button>
    {{ games.format()|safe }}
</div>
<div>
    <h1>Matches</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Players</th>
            <th>Mode</th>
            <th>Map</th>
            <th>Result</th>
            <th>Network</th>
            <th>Imposters</th>
            <th>Panda Count</th>
        </tr>
        {% for match, count in match_counts %}
        <tr>
            <td><button>{{ match.title }}</button></td>
            <td>{{ count }}/{{ match.players }}</td>
            <td>{{ match.mode }}</td>
            <td>{{ match.map }}</td>
            <td>{{ match.result }}</td>
            <td>{{ match.network }}</td>
            <td>{{ match.imposters }}</td>
            <td>{{ match.panda_count }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h1>Players</h1>
    {{ player_stats.format()|safe }}
</div>
<div>
    <h1>Colors</h1>
    {{ color_stats.format()|safe }}
</div>
<div>
    <h1>Correlations</h1>
    {{ correlations.format()|safe }}
</div>
{% endblock %}

templates/user.html
{% extends "base.html" %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}
Hi
{% endblock %}